# Generated by Django 3.2 on 2021-05-16 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vlog',
            fields=[
                ('post_id', models.AutoField(primary_key=True, serialize=False)),
                ('blogtitle', models.TextField(default='', max_length=300)),
                ('blogsubtitle', models.TextField(default='', max_length=200)),
                ('blogcontent', models.TextField(default='')),
                ('pub_date', models.DateField()),
                ('thumbnail', models.ImageField(default='', upload_to='images/')),
            ],
        ),
        migrations.DeleteModel(
            name='Blog',
        ),
    ]
