# Generated by Django 3.2 on 2021-05-16 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20210516_1948'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vlog',
            name='pub_date',
            field=models.DateField(null=True),
        ),
    ]
